name: Daily Release

on:
  schedule:
    - cron: '0 0 * * *' # 每天0点自动运行
  workflow_dispatch: # 允许手动触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.today }}
          name: ${{ steps.date.outputs.today }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"
