name: Daily Release

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行
  workflow_dispatch: # 允许手动触发

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Date
        run: echo "today=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag ${{ env.today }}
          git push origin ${{ env.today }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # 使用个人访问令牌

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.today }}  # 使用创建的标签
          name: Release ${{ env.today }}  # 发布的名称
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}  # 使用个人访问令牌
