name: Update README with Repository Size

on:
  schedule:
    - cron: '* * * * *'  # 每周日运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get Repository Size
      id: get_size
      run: |
        size_kb=$(curl -s https://api.github.com/repos/zjx-kimi/PPTs-in-OI | jq '.size')
        size_mb=$(echo "scale=2; $size_kb/1024" | bc)
        echo "size_mb=${size_mb}" >> $GITHUB_ENV

    - name: Update README.md
      run: |
        sed -i "s/\[X\]/${{ env.size_mb }}/" README.md

    - name: Commit and Push Changes
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add README.md
        git commit -m "Update README with repository size"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
