name: Update README with Repo Size

on:
  push:  # 每次推送到仓库时触发工作流
    branches:
      - master  # 你可以根据需要指定分支
  schedule:
    - cron: '*/1 * * * *'  # 每1分钟触发一次工作流
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to update README
        run: python update_readme.py

      - name: Pull latest changes from the remote repository
        run: git pull --rebase origin master

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest repo size [skip ci]"
          git push
